#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 02:00:00
#SBATCH -J 10_star
#SBATCH --mail-type=ALL
#SBATCH --mail-user Elin.Antonsson.5203@student.uu.se

# Load modules
module load bioinfo-tools
module load star

#Create index
star -- runThreadN 4 --runMode genomeGenerate --genomeSAindexNbases 13 \
--genomeDir /home/elan5203/analysis/10_analysis_star/index \
--genomeFastaFiles /home/elan5203/analysis/4_analysis_pilon/4_pilon_output.fasta


#SRR6040095
STAR --runThreadN 4 --readFilesCommand zcat --genomeDir /home/elan5203/analysis/10_analysis_star/index --readFilesIn /home/elan5203/analysis/7_analysis_trimmomatic/SRR6040095_scaffold_06.1P.trimmed.fastq /home/elan5203/analysis/7_analysis_trimmomatic/SRR6040095_scaffold_06.2P.trimmed.fastq \
--outFileNamePrefix /home/elan5203/analysis/10_analysis_star/output_star_SRR6040095

#SRR6040092
STAR --runThreadN 4 --readFilesCommand zcat --genomeDir /home/elan5203/analysis/10_analysis_star/index --readFilesIn /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6040092_scaffold_06.1.fastq.gz /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6040092_scaffold_06.2.fastq.gz \
--outFileNamePrefix /home/elan5203/analysis/10_analysis_star/output_star_SRR6040092

#SRR6040093
STAR --runThreadN 4 --readFilesCommand zcat --genomeDir /home/elan5203/analysis/10_analysis_star/index --readFilesIn /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6040093_scaffold_06.1.fastq.gz /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6040093_scaffold_06.2.fastq.gz \
--outFileNamePrefix /home/elan5203/analysis/10_analysis_star/output_star_SRR6040093

#SRR6040094
STAR --runThreadN 4 --readFilesCommand zcat --genomeDir /home/elan5203/analysis/10_analysis_star/index --readFilesIn /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6040094_scaffold_06.1.fastq.gz /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6040094_scaffold_06.2.fastq.gz \
--outFileNamePrefix /home/elan5203/analysis/10_analysis_star/output_star_SRR6040094

#SRR6040096
STAR --runThreadN 4 --readFilesCommand zcat --genomeDir /home/elan5203/analysis/10_analysis_star/index --readFilesIn /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6040096_scaffold_06.1.fastq.gz /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6040096_scaffold_06.2.fastq.gz \
--outFileNamePrefix /home/elan5203/analysis/10_analysis_star/output_star_SRR6040096

#SRR6040097
STAR --runThreadN 4 --readFilesCommand zcat --genomeDir /home/elan5203/analysis/10_analysis_star/index --readFilesIn /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6040097_scaffold_06.1.fastq.gz /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6040097_scaffold_06.2.fastq.gz \
--outFileNamePrefix /home/elan5203/analysis/10_analysis_star/output_star_SRR6040097

#SRR6156066
STAR --runThreadN 4 --readFilesCommand zcat --genomeDir /home/elan5203/analysis/10_analysis_star/index --readFilesIn /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6156066_scaffold_06.1.fastq.gz /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6156066_scaffold_06.2.fastq.gz \
--outFileNamePrefix /home/elan5203/analysis/10_analysis_star/output_star_SRR6156066

#SRR6156067
STAR --runThreadN 4 --readFilesCommand zcat --genomeDir /home/elan5203/analysis/10_analysis_star/index --readFilesIn /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6156067_scaffold_06.1.fastq.gz /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6156067_scaffold_06.2.fastq.gz \
--outFileNamePrefix /home/elan5203/analysis/10_analysis_star/output_star_SRR6156067

#SRR6156069
STAR --runThreadN 4 --readFilesCommand zcat --genomeDir /home/elan5203/analysis/10_analysis_star/index --readFilesIn /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6156069_scaffold_06.1.fastq.gz /home/elan5203/data/raw_data/transcriptome/trimmed/SRR6156069_scaffold_06.2.fastq.gz \
--outFileNamePrefix /home/elan5203/analysis/10_analysis_star/output_star_SRR6156069
