#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 25:00:00
#SBATCH -J 12_job_maker2
#SBATCH --mail-type=ALL
#SBATCH --mail-user Elin.Antonsson.5203@student.uu.se

module load bioinfo-tools
module load maker/3.01.1-beta
module load augustus/3.3.3
module load blat

# prepare cdna and species names for augustus:
cdna=/home/elan5203/analysis/11_analysis_trinity/trinity_out_dir/Trinity-GG.fasta
species=durian
genome=/home/elan5203/analysis/4_analysis_pilon/4_pilon_output.fasta

cd /home/elan5203/analysis/12_analysis_maker2_new/4_pilon_output.maker.output/step2
zff2gff3.pl genome.ann | perl -plne 's/\t(\S+)$/\t\.\t$1/' >genome.gff3
# the perl one liner is needed to add an extra GFF column which is missing in the output of zff2gff3.pl

export AUGUSTUS_CONFIG_PATH=/home/elan5203/analysis/12_analysis_maker2_new/4_pilon_output.maker.output/step2/augustus/augustus_config/

# run augustus using autoAug:
autoAug.pl --AUGUSTUS_CONFIG_PATH=/home/elan5203/analysis/12_analysis_maker2_new/4_pilon_output.maker.output/step2/augustus/augustus_config/ --genome=$genome --species=$species --cdna=$cdna --trainingset=genome.gff3 --singleCPU -v --useexisting


