#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 20:00:00
#SBATCH -J 12_job_maker2
#SBATCH --mail-type=ALL
#SBATCH --mail-user Elin.Antonsson.5203@student.uu.se

module load bioinfo-tools
module load maker/3.01.1-beta

cd /home/elan5203/analysis/12_analysis_maker2/

#maker -CTL

#This command created files. I edited the maker_opts.ctl file like this: 
# genome =/home/elan5203/analysis/4_analysis_pilon/4_pilon_output.fasta
# est = /home/elan5203/analysis/11_analysis_trinity/trinity_out_dir/Trinity-GG.fasta
# protein = /home/elan5203/data/raw_data/reference/cotton_reference_UP000032304.fasta
# est2genome = 1
# protein2genome = 1
# cpus = 4

# After these changes I ran the following command: 

maker
