#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 08:00:00
#SBATCH -J 12_job_maker2
#SBATCH --mail-type=ALL
#SBATCH --mail-user Elin.Antonsson.5203@student.uu.se

module load bioinfo-tools
module load maker/3.01.1-beta

#I did all these in different steps, that is why they are all comments now 

#Move to right directory
#cd /home/elan5203/analysis/12_analysis_maker2/4_pilon_output.maker.output/

#Extract results
#gff3_merge -d 4_pilon_output_master_datastore_index.log

#mkdir step3
#cd step3
#Generate necessary files
#maker2zff /home/elan5203/analysis/12_analysis_maker2/4_pilon_output.maker.output/4_pilon_output.all.gff

#Validate sequences
#fathom genome.ann genome.dna -validate > snap_validate_output.txt
#I got the output: 1505 genes, 1504 OK, 613 warnings, 1 errors

#Find erroneous models
#cat snap_validate_output.txt | grep "error"
#I got the output: tig00000244_pilon: MODEL2628 7486 8090 3 + errors(1): cds:internal_stop warnings(2): split-start exon-1:short(1)

#Remove error models
#grep -vwE "MODEL2628" genome.ann > genome.ann2

#Try again, hopefull not find errors
#fathom genome.ann2 genome.dna -validate
#The output tells me that there are no errors.

#Create the remaining output files for training
#fathom genome.ann genome.dna -categorize 1000
#fathom uni.ann uni.dna -export 1000 -plus
#forge export.ann export.dna

#hmm-assembler.pl my_genome . > my_genome.hmm
