#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 15:00:00
#SBATCH -J 12_job_maker2
#SBATCH --mail-type=ALL
#SBATCH --mail-user Elin.Antonsson.5203@student.uu.se

module load bioinfo-tools

module load MUMmer/4.0.0beta2

# Create mummeplot to analyse canu asembly by comparing it to the assembly made in the paper.
nucmer --maxmatch -l 100 -c 100 -p mummer_pilon_assesment_unfiltered \
/home/elan5203/data/raw_data/reference/reference_whole_genome_scaffold_6.fasta \
/home/elan5203/analysis/4_analysis_pilon/4_pilon_output.fasta

delta-filter -i 80 -l 1000 mummer_pilon_assesment_unfiltered.delta > mummer_pilon_assesment.delta

mummerplot --png -p mummer_pilon_assesment mummer_pilon_assesment.delta --layout
