#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 21:00:00
#SBATCH -J 1_job_canu_analysis
#SBATCH --mail-type=ALL
#SBATCH --mail-user Elin.Antonsson.5203@student.uu.se

# Load modules
module load bioinfo-tools
module load canu

# Your commands
canu \
 -p 1_pacbio_assembly_canu -d /home/elan5203/analysis \
 genomeSize=26551601  \
 -pacbio-raw /home/elan5203/data/raw_data/SRR6037732_scaffold_06.fq.gz
