#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 04:00:00
#SBATCH -J 4_pilon_analysis
#SBATCH --mail-type=ALL
#SBATCH --mail-user Elin.Antonsson.5203@student.uu.se

# Load modules
module load bioinfo-tools
module load Pilon

# Your commands
pilon --genome /home/elan5203/analysis/1_analysis_canu/1_pacbio_assembly_canu.contigs.fasta --bam /home/elan5203/analysis/3_analysis_bwa/3_bwa_sorted.bam --output 4_pilon_output --outdir /home/elan5203/analysis/4_analysis_pilon   
