#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:00:00
#SBATCH -J 5_quast_dna
#SBATCH --mail-type=ALL
#SBATCH --mail-user Elin.Antonsson.5203@student.uu.se

# Load modules
module load bioinfo-tools
module load quast

# Your commands
quast.py -R /home/elan5203/data/raw_data/reference/reference_whole_genome_scaffold_6.fasta -o /home/elan5203/analysis/5_analysis_quast_dna/ /home/elan5203/analysis/1_analysis_canu/1_pacbio_assembly_canu.contigs.fasta
