#!/bin/bash -l
#SBATCH -A g2020008
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:30:00
#SBATCH -J 9_fastQC_untrimmed
#SBATCH --mail-type=ALL
#SBATCH --mail-user Elin.Antonsson.5203@student.uu.se

# Load modules
module load bioinfo-tools
module load FastQC

#SRR6040095 aril 1 - before I trimmed it
fastqc -o /home/elan5203/analysis/9_analysis_fastQC_untrimmed /home/elan5203/data/raw_data/transcriptome/untrimmed/SRR6040095_scaffold_06.*
